version: '3'

services:

  db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3

  buybulk:
    build: buybulk
    volumes:
      - ./buybulk:/usr/src/app
    depends_on:
      - db
      - rabbitmq

  amazon:
    build: amazon