version: '3'

services:

  zavkhoz:
    build: zavkhoz
    volumes:
      - ./zavkhoz:/usr/src/app/zavkhoz
      - ./common:/usr/src/app/common
      - common_node_modules:/usr/src/app/common/node_modules
      - zavkhoz_node_modules:/usr/src/app/zavkhoz/node_modules
    depends_on:
      - db
      - rabbitmq

  buybulk:
    build: buybulk
    volumes:
      - ./buybulk:/usr/src/app/buybulk
      - ./common:/usr/src/app/common
      - common_node_modules:/usr/src/app/common/node_modules
      - buybulk_node_modules:/usr/src/app/buybulk/node_modules
    environment:
      - APIFY_LOCAL_STORAGE_DIR=/tmp/apify_data
    depends_on:
      - rabbitmq

  amazon:
    build: amazon
    volumes:
      - ./amazon:/usr/src/app/amazon
      - ./common:/usr/src/app/common
      - common_node_modules:/usr/src/app/common/node_modules
      - amazon_node_modules:/usr/src/app/amazon/node_modules
    depends_on:
      - rabbitmq

  db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
  zavkhoz_node_modules:
  amazon_node_modules:
  buybulk_node_modules:
  common_node_modules:
