version: '3'

services:

  db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3

  buybulk:
    build:
      context: .
      dockerfile: buybulk/Dockerfile
    volumes:
      - ./buybulk:/usr/src/app/buybulk
      - ./common:/usr/src/app/common
    depends_on:
      - db
      - rabbitmq

  amazon:
    build:
      context: .
      dockerfile: amazon/Dockerfile
    volumes:
      - ./amazon:/home/pptruser/app/amazon
      - ./common:/home/pptruser/app/common

volumes:
  mongo_data:
