version: '3'

services:

  zavkhoz:
    build: zavkhoz
    depends_on:
      - db
      - rabbitmq

  buybulk:
    build: buybulk
    environment:
      - APIFY_LOCAL_STORAGE_DIR=/tmp/apify_data
    depends_on:
      - rabbitmq

  amazon:
    build: amazon
    volumes:
      - ./amazon/debug_screenshots:/home/pptruser/app/debug_screenshots
    depends_on:
      - rabbitmq

  db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    build: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
