version: '3'

services:

  zavkhoz:
    build:
      context: .
      dockerfile: zavkhoz/Dockerfile
    volumes:
      - ./zavkhoz:/usr/src/app/zavkhoz
      - ./common:/usr/src/app/common
    depends_on:
      - db
      - rabbitmq

  buybulk:
    build:
      context: .
      dockerfile: buybulk/Dockerfile
    volumes:
      - ./buybulk:/usr/src/app/buybulk
      - ./common:/usr/src/app/common
    environment:
      - APIFY_LOCAL_STORAGE_DIR=/tmp/apify_data
    depends_on:
      - rabbitmq

  amazon:
    build:
      context: .
      dockerfile: amazon/Dockerfile
    volumes:
      - ./amazon:/home/pptruser/app/amazon
      - ./common:/home/pptruser/app/common
    depends_on:
      - rabbitmq

  db:
    image: mongo:4
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
